/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sogou_speech_utils_DataEngine_Callback */

#ifndef _Included_com_sogou_speech_utils_DataEngine_Callback
#define _Included_com_sogou_speech_utils_DataEngine_Callback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
